/**
 * Púca Notes' service worker, WEB ONLY — generated into dist/notes/sw.js by
 * the notes build (vite.notes.config.ts) and registered by
 * src/notes/sw/registerNotesSw.ts with scope `/notes/`.
 *
 * WHY IT CANNOT SHADOW THE MAIN APP. A worker's scope can never be wider than
 * the directory its script is served from unless the server sends a
 * `Service-Worker-Allowed` header, which nothing here does: a worker at
 * /notes/sw.js can never control `/`, Púca's own index.html, its /assets/,
 * or its updater. On top of that, the fetch handler below answers ONLY
 * same-origin GETs under /notes/ — never the API host (cross-origin), never a
 * path outside /notes/ — and lets everything else go to the network untouched.
 *
 * FRESHNESS. Page loads are network-first (a 3 s budget, then the cached
 * page), so an online user always gets the current build and Notes does not
 * trail the task API; hashed assets are cache-first (their names change with
 * their content); every build has its own cache and activating a new worker
 * deletes the old ones. The operator serves this file with
 * `Cache-Control: no-cache` so a CDN cannot pin an old worker
 * (deploy/webapp/README.md; check-versions.sh probes it).
 *
 * The Android Notes app registers NO worker: it serves its page from the APK.
 */

/** The worker's source, with the build id and the files to precache. */
export function renderNotesServiceWorker(buildId, precache) {
    return `/* Púca Notes service worker — generated by scripts/notes-sw.mjs; scope /notes/ */
'use strict';
const BUILD = ${JSON.stringify(buildId)};
const PRECACHE = ${JSON.stringify(precache)};
const CACHE = 'puca-notes-' + BUILD;
const PREFIX = '/notes/';
const INDEX = '/notes/index.html';
const NAV_TIMEOUT_MS = 3000;

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE)
            .then((c) => c.addAll(PRECACHE))
            .catch(() => undefined)
            .then(() => self.skipWaiting()),
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(keys
                .filter((k) => k.startsWith('puca-notes-') && k !== CACHE)
                .map((k) => caches.delete(k))))
            .then(() => self.clients.claim()),
    );
});

/** Which requests this worker answers at all. Everything else: untouched. */
function handles(request) {
    if (request.method !== 'GET') return false;
    let url;
    try { url = new URL(request.url); } catch (_) { return false; }
    if (url.origin !== self.location.origin) return false;   // never the API host
    if (!url.pathname.startsWith(PREFIX)) return false;      // never the main app
    if (url.pathname === PREFIX + 'sw.js') return false;
    return true;
}

async function networkFirst(request, fallbackToIndex) {
    const cache = await caches.open(CACHE);
    try {
        const response = await Promise.race([
            fetch(request),
            new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), NAV_TIMEOUT_MS)),
        ]);
        if (response && response.ok && response.type === 'basic') {
            const copy = response.clone();
            cache.put(fallbackToIndex ? INDEX : request, copy).catch(() => undefined);
        }
        return response;
    } catch (err) {
        const hit = await cache.match(fallbackToIndex ? INDEX : request);
        if (hit) return hit;
        throw err;
    }
}

async function cacheFirst(request) {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request);
    if (hit) return hit;
    const response = await fetch(request);
    if (response && response.ok && response.type === 'basic') cache.put(request, response.clone()).catch(() => undefined);
    return response;
}

self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (!handles(request)) return;
    const path = new URL(request.url).pathname;
    if (request.mode === 'navigate') {
        event.respondWith(networkFirst(request, true));
    } else if (path.startsWith(PREFIX + 'assets/')) {
        event.respondWith(cacheFirst(request));
    } else {
        event.respondWith(networkFirst(request, false));
    }
});
`;
}

/**
 * The vite plugin: after the WEB notes build has written its files, list
 * everything in dist/notes/ (the page, its assets, and the manifest and icons
 * the main build copied there) and write sw.js beside them. The native build
 * gets nothing.
 */
export function notesServiceWorkerPlugin({ outDir, enabled }) {
    return {
        name: 'puca-notes-service-worker',
        apply: 'build',
        async closeBundle() {
            if (!enabled) return;
            const fs = await import('node:fs');
            const path = await import('node:path');
            const crypto = await import('node:crypto');
            const files = [];
            const walk = (dir) => {
                for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
                    const full = path.join(dir, e.name);
                    if (e.isDirectory()) walk(full);
                    else files.push(path.relative(outDir, full).split(path.sep).join('/'));
                }
            };
            walk(outDir);
            const precache = files
                .filter((f) => f !== 'sw.js' && !f.endsWith('.map'))
                .sort()
                .map((f) => (f === 'index.html' ? '/notes/index.html' : `/notes/${f}`));
            const index = fs.readFileSync(path.join(outDir, 'index.html'), 'utf8');
            const buildId = crypto.createHash('sha256').update(index).update(precache.join('\n')).digest('hex').slice(0, 16);
            fs.writeFileSync(path.join(outDir, 'sw.js'), renderNotesServiceWorker(buildId, precache));
        },
    };
}
